### ISSUE TITLE
Allow to set the ingress tls secretName

### ISSUE THREAD

**Issue by anbraten** [gimlet-io/onechart#117]
For wildcard deployments we already have a tls-secret and would like to reuse it for multiple deployments. Therefore it would be helpful to have an option like `ingress.tls.secretName`.

PS: pretty cool approach. I had a short test on creating a cli tool to deploy a local project by building the image, automatically pushing it to some configured registry and deploying it using onechart.

**Comment by anbraten** [comment]
Okay after reading again this seems to be already working, I was just missing the `-` 🤦🏾 . 

This seems to work:

```yml
ingress:
  tlsEnabled: true
  host: example.com
  tls:
    - secretName: tls-my-wildcard
```

**Comment by laszlocph** [comment]
What about?

```yaml
#values.yaml
ingress:
  host: xxx
  tlsEnabled: true
  secretName: tls-internal
```

**Comment by anbraten** [comment]
That would work for me. Should I open a PR?

**Comment by laszlocph** [comment]
I mean it is working today like this.

**Comment by anbraten** [comment]
Using the values you suggested and `helm template my-release onechart/onechart -f onechart.yaml` I get:

```yml
---
# Source: onechart/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-release
  namespace: default
  labels:
    helm.sh/chart: onechart-0.64.0
    app.kubernetes.io/name: onechart
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/managed-by: Helm
spec:
  tls:
    - hosts:
        - "xxx"
      secretName: tls-my-release
  rules:
    - host: "xxx"
      http:
        paths:
          - path: "/"
            pathType: "Prefix"
            backend:
              service:
                name: my-release
                port:
                  number: 80
```
