### ISSUE TITLE
add nfs volume mount

### ISSUE THREAD

**Issue by WladyX** [gimlet-io/onechart#123]
NFS volume support seems missing, I've tried getting it to work with podspec, but did not manage.
Thank you for sharing this project!

**Comment by laszlocph** [comment]
I am happy to assist you in your efforts, but in general NFS support feels a bit too specific for OneChart. I may be wrong, but let's see the yaml first before we make the decision. PodSpec could be a solution here.

**Comment by WladyX** [comment]
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx-web-pod
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: web-files
          mountPath: /usr/share/nginx/html
  volumes:
    - name: web-files
      nfs:
        server: 10.10.10.15
        path: /path/to/nfs/share
```

let's take this for example, with podspec I could generate the volumes part, but not the volumeMounts.
Thank you!

**Comment by WladyX** [comment]
managed to get it work like this:
```
image:
  repository: my-app
  tag: fd803fc
vars:
  VAR_1: "value 1"
  VAR_2: "value 2"
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
  host: my-app.mycompany.com

podSpec:
  hostNetwork: true
  volumes:
    - name: test-volume
      nfs:
        server: my-nfs-server.example.com
        path: /my-nfs-volume
        readOnly: true
container:
  volumeMounts:
    - mountPath: /my-nfs-data
      name: test-volume
```

maybe it will help somebody else, feel free to close the ticket if you don't wish to implement this natively.
thank you for your support!
