### ISSUE TITLE
[charts/onechart] Allow defining UDP ports

### ISSUE THREAD

**Issue by davidfrickert** [gimlet-io/onechart#124]
Currently it is not possible to define UDP ports. All ports in the service created are TCP hardcoded.

Allow values ports to define protocol, if not defined then TCP by default?

```
ports:
  - svcPort: 8384
    targetPort: 8384
  - svcPort: 22000
    targetPort: 22000
    protocol: UDP
  - svcPort: 22000
    targetPort: 22000
    protocol: TCP
  - svcPort: 21027
    targetPort: 21027
    protocol: UDP
```
