### ISSUE TITLE
cpu disable limit

### ISSUE THREAD

**Issue by WladyX** [gimlet-io/onechart#139]
Is it possible to ignore only the CPU limit?
I would like to set a limit for memory but no limit for CPU, is that possible?
I have tried with `cpu: null` and `cpu: {}` but the schema says this is required, I know I can ignore the limits, but I don't want to ignore the memory limit.
Thank you!

**Comment by laszlocph** [comment]
You have `resources.ignore` and `resources.ignoreLimits` but if you specify something like 

```
resources:
  requests:
    memory: "64Mi"
  limits:
    memory: "128Mi"
```

OneChart will add a cpu limit from the default values.yaml. That said not providing CPU limits at this moment is not possible. It should be though as it is a common pattern.
