### ISSUE TITLE
onechart/cron-job doesn't support pod annotations

### ISSUE THREAD

**Issue by YoucefGuichi** [gimlet-io/onechart#146]
```yaml
  jobTemplate:
    spec:
      template:
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- range . }}
            - name: {{ . }}
            {{- end }}
          {{- end }}
          restartPolicy: Never
```
