### ISSUE TITLE
PVC should not be create for secret volumes

### ISSUE THREAD

**Issue by vtmocanu** [gimlet-io/onechart#148]
similar on how PVCs ignore `.existingConfigMap`, think you should also add `.existingSecret` so that a PVC is not created for mounting a secret

**Comment by davidfrickert** [comment]
Just had the same issue, i think PR #151 that I just published should fix it (plus bumping chart versions of course)

**Comment by davidfrickert** [comment]
as a workaround until this fix is released, you can use the following workaround:

```
      volumes:
      - name: config
        path: /config/config.yml
        subPath: config.yml
        existingSecret: secret
        existingClaim: dummy

```

by using existingClaim to a dummy value, the pvc won't be created, and it won't be used at all because existingSecret is used for the mount as it has precedence in the template.

**note: only tested that this works on the cron job chart, dont know if it works on the regular one.**
