### ISSUE TITLE
Fix non valid yaml

### ISSUE THREAD

**Issue by laszlocph** [gimlet-io/onechart#2]
We should add more ifs in the template to not generate nil fields like `volumes:` bellow.

```
      containers:
        - name: fosdem-2021
          securityContext:
            {}
          image: "xxx"
          imagePullPolicy: 
          envFrom:
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 200m
              memory: 200Mi
      volumes:
```
