### ISSUE TITLE
Transition from rollingUpdate to Recreate hits a kubectl shortcoming

### ISSUE THREAD

**Issue by laszlocph** [gimlet-io/onechart#35]
We use the recreate strategy when a volume is defined.

https://github.com/kubernetes/kubernetes/issues/24198

**Comment by laszlocph** [comment]
```yaml
  strategy:
    rollingUpdate: null
    type: Recreate
```

Seems to solve the issue with kubectl apply.

It doesn't seem to work in Flux though.
