### ISSUE TITLE
Investigate if OneChart can be rendered to Cloud Run / KNative serving API

### ISSUE THREAD

**Issue by laszlocph** [gimlet-io/onechart#49]
- Values files for OneChart carry all meaningful info that is needed for a containerized deployment to work
- OneChart is a Helm chart. `helm template` renders the chart into plain text.

The above two statements suggests that we can make a Helm chart that renders KNative serving API yamls. Not Kubernetes yamls, but yamls that KNative and Google Cloud Run understands.

The goal of this issue is to render a basic KNative manifest that is driven by a OneChart values file, like the following:

```yaml
image:
  repository: nginx
  tag: latest
replicas: 3
containerPort: 5000
vars:
  DUMMY: "test-me"
```

and after a `helm template` command, the result can be deployed to Google Cloud Run.

Some info:
- https://ahmet.im/blog/cloud-run-is-a-knative/
- https://knative.dev/docs/reference/api/serving-api/

When we are done, we should review  the project by KNative community members: salaboy and tvitale
