### ISSUE TITLE
Adding promtheus scraping?

### ISSUE THREAD

**Issue by moshez** [gimlet-io/onechart#62]
Since the chart already supports (optional) prometheus rules, would it make sense to support (optional) Prometheus service scraping?

The following is not debugged, just a rough draft to show what I mean:

```yaml
{{ if .Values.monitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "robustName" .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
  {{- if or .Values.gitRepository .Values.gitSha }}
  annotations:
    {{- if .Values.gitRepository }}
    gimlet.io/git-repository: {{ .Values.gitRepository }}
    {{- end }}
    {{- if .Values.gitSha }}
    gimlet.io/git-sha: {{ .Values.gitSha }}
    {{- end }}
  {{- end }}
spec:
  endpoints:
  - interval: 60s
    params:
      format:
      - prometheus
    path: /metrics # TBD: Needs to also be templated-with-default
    {{ if .Values.monitor.portName }}
    name: {{ .Values.monitor.portName }}
    {{- else if not .Values.ports }}
    name: http
    {{ else }}
    name: {{ Values.ports[0].name }}
    {{ endif }}
    scheme: {{ .Values.monitor.scheme or "http" }}
    {{ if .Values.monitor.scrapeTimeout }}
    scrapeTimeout: {{ .Values.monitor.scrapeTimeout }}
    {{ end }}
  namespaceSelector:
    matchNames:
    - "{{ .Release.Namespace }}"
  selector:
    {{- include "helm-chart.selectorLabels" . | nindent 4 }}
{{ end }}
```
