### ISSUE TITLE
Request for HPA Support Contribution

### ISSUE THREAD

**Issue by super-kishik** [gimlet-io/onechart#91]
I am interested in contributing to the project and would like to propose the addition of Horizontal Pod Autoscaling (HPA) support. Before investing time in the development, I want to discuss the feasibility and gather feedback from the maintainers and the community.

```

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 4

    
  metrics:
  - resource:
      name: cpu
      target: 
        type: Utilization
        averageUtilization: 70
    type: Resource
  - resource:
      name: memory
      target: 
        type: Utilization
        averageUtilization: 85
    type: Resource

```

thank you
