### ISSUE TITLE
[charts/onechart] Specifying ports in values doesn't work as expected

### ISSUE THREAD

**Issue by davidfrickert** [gimlet-io/onechart#92]
Specifying ports in values doesn't work as expected.

E.g.:

```
ports:
  - name: 445
    svcPort: 445
```

The template tries to fill the `name` in both the actual name and in `targetPort`, which doesn't work, as port needs to be a number and name needs to be a string:
```
Error: INSTALLATION FAILED: Service in version "v1" cannot be handled as a Service: json: cannot unmarshal number into Go struct field ServicePort.spec.ports.name of type string
``` 

https://github.com/gimlet-io/onechart/blob/906958cbcc85ed4f81cffdd72fbb65f94f15d904/charts/onechart/templates/service.yaml#L65-L73

Instead, maybe support passing `targetPort`?

```
ports:
  - name: tcp-445
    svcPort: 445
    targetPort: 445
```

### Offtopic
Name could also be optional:

```
ports:
  - svcPort: 445
    targetPort: 445
```

The template could then fill the port name with a concatenation of tcp and the port.

**Comment by laszlocph** [comment]
Hello @davidfrickert 

`.Values.ports` is an undocumented feature, and honestly we forgot why it is in Onechart in the first place.

But the following values file produces valid yaml, and seemingly we support multiple ports.

```yaml
ports:
  - name: blabla
    containerPort: 445
  - name: blabla2
    containerPort: 446

containerPort: 446
```

You are right about the fact that the template tries to fill the name in both the actual name and in targetPort. TargetPort can be a string and OneChart produces internally consistent yaml.

So the question is, is there something we don't support? Why did you want to provide a port number as name and not a string?
